#!/bin/bash

#cd

#mkdir tensorflow
#cd tensorflow
#git clone https://github.com/tensorflow/models.git

#sudo apt-get install protobuf-compiler python-pil python-lxml
#sudo pip install jupyter
#sudo pip install matplotlib

#cd ~/tensorflow/models/research

#From tensorflow/models/research
#protoc object_detection/protos/*.proto --python_out=.

# From tensorflow/models/
#export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
